### ISSUE TITLE
Migrate from travis-ci and bintray to github actions and maven central

### ISSUE THREAD

**Issue by christiansiegel** [baloise/jenkins-maven-plugin#3]
travis-ci.**org** will be closed down December 31st, 2020

Announcement: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom
Migration guide: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by culmat** [comment]
see https://github.com/baloise/ossrh-pipeline-demo
